---
- name: Install Grafana
  hosts: slave2
  become: yes
  vars:
    grafana_apt_key_url: "https://packages.grafana.com/gpg.key"
    grafana_repo_url: "deb https://packages.grafana.com/oss/deb stable main"
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Add Grafana APT repository key
      apt_key:
        url: "{{ grafana_apt_key_url }}"

    - name: Add Grafana APT repository
      apt_repository:
        repo: "{{ grafana_repo_url }}"
        state: present
        update_cache: yes

    - name: Install Grafana
      apt:
        name: grafana
        state: present

    - name: Start Grafana service
      service:
        name: grafana-server
        state: started
        enabled: yes
